wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1718272163
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 23
      4: 3.12.3
      5: 0.17.0
      6: 4.40.2
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
